import { useEffect, useState } from "react";
import { Tile3DLayer } from "@deck.gl/geo-layers";

interface Props {
  visible: boolean;
  tilesetUrl?: string;
}

/**
 * Deck.gl Tile3DLayer wrapper for 3D Tiles (CityGML / b3dm) streaming.
 *
 * Consumes the tileset.json generated by `apps/api/src/tools/build3DTiles.ts`.
 * Falls back gracefully if no tileset URL is provided.
 */
export function useTile3DLayer({ visible, tilesetUrl }: Props) {
  const [tilesetLoaded, setTilesetLoaded] = useState(false);

  useEffect(() => {
    if (!visible || !tilesetUrl) return;
    // Deck.gl handles tileset loading internally; this hook is for future
    // extension (e.g. dynamic styling based on tile load state).
    setTilesetLoaded(false);
  }, [visible, tilesetUrl]);

  if (!visible || !tilesetUrl) return null;

  return new Tile3DLayer({
    id: "tile-3d-layer",
    data: tilesetUrl,
    // loaders.gl 3d-tiles loader auto-detected by deck.gl
    onTilesetLoad: (ts: unknown) => {
      setTilesetLoaded(true);
      console.log("[Tile3DLayer] Tileset loaded", ts);
    },
    onTileLoad: (tile: unknown) => {
      void tile;
    },
    onTileError: (err: unknown) => {
      console.error("[Tile3DLayer] Tile error", err);
    },
    pointSize: 1,
    getPointColor: [255, 255, 255],
    getFillColor: [200, 200, 210, 200],
    pickable: true,
    _: { tilesetLoaded }, // keep linter happy
  });
}
