import { useEffect, useState } from "react";
import { Tile3DLayer } from "@deck.gl/geo-layers";

interface Props {
  visible: boolean;
  tilesetUrl?: string;
}

/**
 * Deck.gl Tile3DLayer wrapper for 3D Tiles (CityGML / b3dm) streaming.
 *
 * Consumes the tileset.json generated by `apps/api/src/tools/build3DTiles.ts`.
 * Falls back gracefully if no tileset URL is provided.
 *
 * Styling: warm concrete tones with sky-blue glass accents so the buildings
 * read as real city fabric against the dark basemap.
 */
export function useTile3DLayer({ visible, tilesetUrl }: Props) {
  const [tilesetLoaded, setTilesetLoaded] = useState(false);

  useEffect(() => {
    if (!visible || !tilesetUrl) return;
    setTilesetLoaded(false);
  }, [visible, tilesetUrl]);

  if (!visible || !tilesetUrl) return null;

  return new Tile3DLayer({
    id: "tile-3d-layer",
    data: tilesetUrl,
    onTilesetLoad: (ts: unknown) => {
      setTilesetLoaded(true);
      console.log("[Tile3DLayer] Tileset loaded", ts);
    },
    onTileLoad: (tile: unknown) => {
      void tile;
    },
    onTileError: (err: unknown) => {
      console.error("[Tile3DLayer] Tile error", err);
    },
    // Styling — warm concrete with subtle blue glass tint
    getFillColor: [210, 215, 225, 235] as [number, number, number, number],
    getLineColor: [180, 190, 210, 160] as [number, number, number, number],
    pointSize: 1,
    getPointColor: [255, 255, 255],
    pickable: true,
    // Make 3D tiles slightly more prominent than extruded GeoJSON
    opacity: 0.95,
    _: { tilesetLoaded },
  });
}
